### ISSUE TITLE
Processed reference

### ISSUE THREAD

**Issue by cc111111** [CupCupRay/Bin2Summary#1]
Halo,  how can I get the processed reference for training? or the process script {comment_preprocess.py} mentioned in README of  SourceCode dataset?

**Comment by CupCupRay** [comment]
Hi, @cc111111,

Thank you for your interest!

I have uploaded the script to conduct functionality description embedding. For your convenience, I also uploaded a raw comment reference extracted from our source codes datasets (of course, you can try to generate your own raw comment reference using the source codes). 

Hope this will answer your question.

Best regards,
Ray

**Comment by cc111111** [comment]
Thanks for your prompt response, I get it!
