### ISSUE TITLE
dataset property

### ISSUE THREAD

**Issue by linjikun1** [CupCupRay/Bin2Summary#3]
Hi,

- I would like to know in what architecture the [Raw binaries for dataset](https://drive.google.com/drive/folders/1ZgmuB5T2Ho5NRmJLozpUcmWvsEt3YxUT) you provided are compiled.

- I would like to know whether or not the raw binaries have been strip-processed.

Thank you!

**Comment by CupCupRay** [comment]
Hi, @ljk419511,

The raw binaries provided in our repository are built based on Windows-x86_64, and they are not stripped yet (so we call them "raw" binaries). If you want to use them in the experiment, you should strip them first.

Hope this will answer your question.

Best regards,
Ray
